spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microconfig-test-dev
---
spring:
  profiles: default
  application:
    name: mircroconfig-test-default
